BUILD_DIR	?= ./build

# standard targets
.PHONY: all
all: $(NAME)

.PHONY: clean
clean:

.PHONY: fclean
fclean: clean

.PHONY: re
re: fclean all

# default-target = "hello"
NAME		:= hello

$(NAME): hello
