name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfiles: ['epitest.dockerfile', 'ubuntu.dockerfile']

    steps:
      - uses: actions/checkout@v2
      - name: build image
        run: docker build . -f ci/${{ matrix.dockerfiles }} -t epine
      - name: run image
        run: docker run epine

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo build
